# Generated by Django 5.2 on 2025-05-16 20:10

import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_color_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.CharField(default=teams.models.get_random_color, max_length=10),
        ),
    ]
