# Generated by Django 5.2 on 2025-05-18 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_team_member_alter_team_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_member',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
