# Generated by Django 5.2 on 2025-06-21 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_team_team_member_alter_team_updated_at'),
        ('users', '0002_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_member',
            field=models.ManyToManyField(blank=True, related_name='member_teams', through='users.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
