# Generated by Django 5.2 on 2025-07-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_team_team_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-created_at', 'name'), 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
    ]
