# Generated by Django 5.2 on 2025-07-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_teaminvitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminvitation',
            unique_together=set(),
        ),
    ]
