# Generated by Django 5.2 on 2025-08-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_alter_teaminvitation_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaminvitation',
            options={'ordering': ('-created_at',), 'verbose_name': 'Приглашение', 'verbose_name_plural': 'Приглашения'},
        ),
    ]
