# Generated by Django 5.2 on 2025-05-19 05:17

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default=projects.models.get_random_color, max_length=10),
        ),
    ]
