# Generated by Django 5.2 on 2025-05-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('В работе', 'In Work'), ('Приостановлен', 'Stopped'), ('Завершён', 'Completed')], default='В работе', max_length=20),
        ),
    ]
