# Generated by Django 5.2 on 2025-06-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_project_members_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_members',
        ),
    ]
