# Generated by Django 5.2 on 2025-06-26 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_project_members'),
        ('users', '0004_projectmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(blank=True, related_name='project_membership', through='users.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
