# Generated by Django 5.2 on 2025-07-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_project_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at', 'name'), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
