# Generated by Django 5.2 on 2025-05-30 18:30

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default=tasks.models.get_random_color, max_length=10),
        ),
    ]
