# Generated by Django 5.2 on 2025-05-31 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tag_task_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bg_color', models.CharField(max_length=50)),
                ('text_color', models.CharField(max_length=50)),
                ('border_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color_class',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tagcolor'),
        ),
    ]
