# Generated by Django 5.2 on 2025-06-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tagcolor_remove_tag_color_class_tag_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagColor',
            new_name='Color',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.color')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='tasks.status'),
        ),
    ]
