# Generated by Django 5.2 on 2025-06-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_tagcolor_color_status_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='Новая', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='tasks.status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='tags', to='tasks.tag'),
        ),
    ]
