# Generated by Django 5.2 on 2025-06-02 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_project_members_alter_project_description'),
        ('tasks', '0008_alter_task_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
