# Generated by Django 5.2 on 2025-06-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_tag_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_name',
            field=models.CharField(default='Зелёный', max_length=50),
            preserve_default=False,
        ),
    ]
