# Generated by Django 5.2 on 2025-06-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_color_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Самый высокий', 'Highest'), ('Высокий', 'High'), ('Средний', 'Medium'), ('Низкий', 'Low'), ('Самый низкий', 'Lowest'), ('Не указан', 'Not Specified')], default='Не указан', max_length=20),
        ),
    ]
