# Generated by Django 5.2 on 2025-06-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
