# Generated by Django 5.2 on 2025-06-11 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_project_members_alter_project_description'),
        ('tasks', '0012_status_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='projects.project'),
        ),
    ]
