# Generated by Django 5.2 on 2025-06-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_project_members_alter_project_description'),
        ('tasks', '0013_status_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.color'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.color'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='Новая', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='tasks.status'),
        ),
    ]
