# Generated by Django 5.2 on 2025-07-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_color_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskimage',
            options={'ordering': ('-uploaded_at',), 'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
    ]
