# Generated by Django 5.2 on 2025-08-06 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, default='Новая', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='tasks.status'),
        ),
    ]
