# Generated by Django 5.2 on 2025-08-03 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0008_alter_project_options'),
        ('tasks', '0019_alter_taskimage_options'),
        ('teams', '0012_alter_teaminvitation_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('team_changed', 'Изменения в команде'), ('team_member_joined', 'Присоединение к команде'), ('team_member_left', 'Покинул команду'), ('project_created', 'Создание проекта'), ('project_changed', 'Изменения проекта'), ('project_deleted', 'Удаление проекта'), ('task_created', 'Создана задача'), ('task_deleted', 'Задача удалена'), ('tack_changed', 'Изменение задачи'), ('task_executor_changed', 'Изменены исполнители'), ('tag_created', 'Создан тег'), ('tag_deleted', 'Удалён тег'), ('task_tag_changed', 'У задачи поменялись теги'), ('status_created', 'Создан статус'), ('status_deleted', 'Статус удалён'), ('comment_created', 'Создан комментарий'), ('comment_deleted', 'Комментарий удалён')], max_length=100)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История действия',
                'verbose_name_plural': 'История действий',
            },
        ),
    ]
