# Generated by Django 5.2 on 2025-08-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'История действия', 'verbose_name_plural': 'История действий'},
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('team_deleted', 'Команда удалена'), ('team_changed_name', 'Изменение названия команды'), ('team_changed_description', 'Изменение описание команды'), ('team_changed_photo', 'Изменение фото команды'), ('team_member_joined', 'Присоединение к команде'), ('team_member_role_changed', 'Изменение роли'), ('team_member_left', 'Покинул команду'), ('project_created', 'Создание проекта'), ('project_changed_name', 'Изменение названия проекта'), ('project_changed_description', 'Изменение описание проекта'), ('project_changed_photo', 'Изменение фото проекта'), ('project_changed_status', 'Изменение статуса проекта'), ('project_deleted', 'Удаление проекта'), ('task_created', 'Создана задача'), ('subtask_created', 'Создана подзадача'), ('task_deleted', 'Задача удалена'), ('team_changed_name', 'Изменение названия задачи'), ('team_changed_description', 'Изменение описания задачи'), ('team_changed_status', 'Изменение статуса задачи'), ('team_changed_priority', 'Изменение приоритета задачи'), ('task_executor_changed', 'Изменены исполнители'), ('task_no_executor', 'Исполнителей нет'), ('tag_created', 'Создан тег'), ('tag_deleted', 'Удалён тег'), ('task_tag_changed', 'У задачи поменялись теги'), ('status_created', 'Создан статус'), ('status_deleted', 'Статус удалён'), ('comment_created', 'Создан комментарий'), ('comment_deleted', 'Комментарий удалён')], max_length=100),
        ),
    ]
