# Generated by Django 5.2 on 2025-08-05 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_actionlog_options_alter_actionlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='logs_visible_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
