# Generated by Django 5.2 on 2025-06-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_projectmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='team',
            new_name='project',
        ),
    ]
