# Generated by Django 5.2 on 2025-07-16 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='users.profile'),
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VKontakte'), ('github', 'GitHub')], max_length=20)),
                ('link', models.URLField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='users.profile')),
            ],
        ),
    ]
