# Generated by Django 5.2 on 2025-07-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_tag_profile_socialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='network',
            field=models.CharField(choices=[('Telegram', 'Telegram'), ('VK', 'VKontakte'), ('GitHub', 'GitHub')], max_length=20),
        ),
    ]
