# Generated by Django 5.2 on 2025-07-22 18:26

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_project_members'),
        ('users', '0008_alter_socialnetwork_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default=users.models.get_random_color, max_length=25),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm', to='projects.project'),
        ),
    ]
