# Generated by Django 5.2 on 2025-07-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tag_color_alter_projectmember_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialnetwork',
            unique_together={('profile', 'network')},
        ),
    ]
