# Generated by Django 5.2 on 2025-07-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_socialnetwork_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': ('-date_joining',), 'verbose_name': 'Участник проекта', 'verbose_name_plural': 'Участники проектов'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ('network',), 'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('-date_joining',), 'verbose_name': 'Участник команды', 'verbose_name_plural': 'Участники команд'},
        ),
    ]
