# Generated by Django 5.2 on 2025-07-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_taskimage_options'),
        ('users', '0011_alter_profile_options_alter_projectmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='taskexecutor',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='taskexecutor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execs', to=settings.AUTH_USER_MODEL),
        ),
    ]
