# Generated by Django 5.2 on 2025-07-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_profile_picture_alter_taskexecutor_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профил', 'verbose_name_plural': 'Профили'},
        ),
    ]
