# Generated by Django 5.2 on 2025-08-01 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_teammember_team_alter_teammember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('Creator', 'Создатель'), ('Admin', 'Администратор'), ('Member', 'Участник'), ('Viewer', 'Наблюдатель')], default='Viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
