# Generated by Django 5.2 on 2025-08-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_teammember_role_alter_projectmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('Creator', 'Создатель'), ('Admin', 'Администратор'), ('Manager', 'Менеджер'), ('Member', 'Участник'), ('Viewer', 'Наблюдатель')], default='Viewer', max_length=20),
        ),
    ]
