# Generated by Django 5.2 on 2025-08-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_teammember_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
