# Generated by Django 5.2 on 2025-08-05 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_task_project'),
        ('users', '0018_delete_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecutor',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='taskexecutor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
