# Generated by Django 5.2 on 2025-08-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_taskexecutor_task_alter_taskexecutor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_number',
            field=models.BooleanField(default=False),
        ),
    ]
